name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What type of bump?"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  test:
    name: Test on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - name: Install poetry
        run: pipx install poetry==1.3.1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest

  bump:
    name: Bump
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Bump version
        run: poetry version ${{ inputs.version }}
      # - name: Build
      #   run: poetry build

      # TODO: make a release, and tag the build output
